import 'dart:convert';
import 'dart:io';

import 'package:emberkeep/content/space_themes.dart';
import 'package:emberkeep/content/titles.dart';
import 'package:emberkeep/engine.dart';
import 'package:emberkeep/models.dart';
import 'package:emberkeep/social.dart';
import 'package:emberkeep/tokens.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

String _firestoreRules() {
  final file = File('firestore.rules');
  expect(
    file.existsSync(),
    isTrue,
    reason: 'Run this test from the Flutter package root.',
  );
  return file.readAsStringSync();
}

Set<String> _singleQuotedValues(String source) => RegExp(
  r"'([^']+)'",
).allMatches(source).map((match) => match.group(1)!).toSet();

RegExp _publishedTitlePattern(String rules) {
  final match = RegExp(
    r"return\s+title\.matches\(\s*'([^']+)'\s*\)",
    dotAll: true,
  ).firstMatch(rules);
  expect(match, isNotNull, reason: 'validBuildTitle must remain inspectable.');
  return RegExp(match!.group(1)!);
}

Iterable<Map<Stat, int>> _currentBuildShapes() sync* {
  // Blank slate, every solo title, and every two-domain title.
  yield const {};
  for (final stat in Stat.values) {
    yield {stat: 1};
  }
  for (var first = 0; first < Stat.values.length; first++) {
    for (var second = first + 1; second < Stat.values.length; second++) {
      yield {Stat.values[first]: 1, Stat.values[second]: 1};
    }
  }

  // Every current rank-prefix family, while keeping a second domain close
  // enough that BuildTitles still emits a pair title rather than a solo one.
  for (var index = 0; index < Stat.values.length; index++) {
    yield {
      Stat.values[index]: 50,
      Stat.values[(index + 1) % Stat.values.length]: 17,
    };
  }
}

GameState _stateWithBuild(Map<Stat, int> shape) {
  final state = GameState();
  for (final stat in Stat.values) {
    state.stats[stat] = shape[stat] ?? 0;
  }
  return state;
}

void main() {
  group('shared-space payload contract', () {
    test('every current room identity is emitted without schema drift', () {
      final rules = _firestoreRules();
      final keyBlock = RegExp(
        r'd\.keys\(\)\.hasOnly\(\[(.*?)\]\)',
        dotAll: true,
      ).firstMatch(rules);
      expect(keyBlock, isNotNull);
      final ruleKeys = _singleQuotedValues(keyBlock!.group(1)!);
      final payloadKeys = ruleKeys.difference(const {'uid', 'updatedAt'});

      final wallBlock = RegExp(
        r'&&\s+d\.wall\s+in\s+\[(.*?)\]',
        dotAll: true,
      ).firstMatch(rules);
      expect(wallBlock, isNotNull);
      final allowedWalls = _singleQuotedValues(wallBlock!.group(1)!);

      for (final theme in spaceThemes) {
        final state = GameState()..wallStyle = theme.id;
        final payload = roomDisplay(state);

        expect(payload['wall'], theme.id, reason: theme.name);
        expect(allowedWalls, contains(theme.id), reason: theme.name);
        expect(payload.keys.toSet(), payloadKeys, reason: theme.name);
        expect(payload['v'], 3, reason: theme.name);
      }
    });

    test('every current generated build title is accepted by source rules', () {
      final titlePattern = _publishedTitlePattern(_firestoreRules());
      final titles = <String>{};

      for (final shape in _currentBuildShapes()) {
        final state = _stateWithBuild(shape);
        final expected = BuildTitles.epithetOf(state.stats);
        final published = roomDisplay(state)['title'];
        titles.add(expected);

        expect(published, expected);
        expect(
          titlePattern.hasMatch(expected),
          isTrue,
          reason: '$expected is generated by the app but rejected by rules',
        );
      }

      expect(titles, containsAll(const ['STEADY HAND', 'OPEN HOUSE']));
      expect(titles, hasLength(28));
    });

    test(
      'profile fields are always present but stay empty without consent',
      () {
        const privateName = 'A name that stays on this device';
        const privateIntro = 'A private introduction for my own room.';
        const privateGoal = 'A goal I did not consent to share';
        final state = GameState()..playerName = privateName;
        state.goals.add(Goal(title: privateGoal, stat: Stat.vit, target: 12));
        state.setSpaceProfile(intro: privateIntro, goals: const [privateGoal]);

        final payload = roomDisplay(state);
        final encoded = jsonEncode(payload);

        expect(payload['v'], 3);
        expect(payload['name'], 'Fellow keeper');
        expect(payload['profileVisible'], isFalse);
        expect(payload['displayName'], isEmpty);
        expect(payload['about'], isEmpty);
        expect(payload['featuredGoals'], isEmpty);
        expect(encoded, isNot(contains(privateName)));
        expect(encoded, isNot(contains(privateIntro)));
        expect(encoded, isNot(contains(privateGoal)));
      },
    );

    test('an explicitly shared profile is sanitized and tightly bounded', () {
      final state = GameState()
        ..shareSpaceProfile = true
        ..playerName = '  Mika\n${'x' * 80}  '
        ..spaceIntro = '  A room\nwith\tbreathing space. ${'y' * 220}  '
        ..featuredGoalTitles.addAll([
          '  Finish\nthis room  ',
          'z' * 140,
          '  A third goal  ',
          'A fourth goal that must not publish',
        ]);

      final payload = roomDisplay(state);
      final goals = (payload['featuredGoals'] as List).cast<String>();

      expect(payload['profileVisible'], isTrue);
      expect(payload['displayName'], startsWith('Mika '));
      expect(
        (payload['displayName'] as String).runes.length,
        lessThanOrEqualTo(40),
      );
      expect(payload['displayName'], isNot(contains('\n')));
      expect((payload['about'] as String).runes.length, lessThanOrEqualTo(180));
      expect(payload['about'], isNot(anyOf(contains('\n'), contains('\t'))));
      expect(goals, hasLength(3));
      expect(goals.first, 'Finish this room');
      expect(goals[1].runes.length, 100);
      expect(goals.last, 'A third goal');
      expect(goals, isNot(contains('A fourth goal that must not publish')));
    });

    test(
      'hidden visitor-eligible cards publish empty values, not less consent',
      () {
        final state = GameState()
          ..shareSpaceProfile = true
          ..playerName = 'Mika'
          ..spaceIntro = 'A room for making things.'
          ..featuredGoalTitles.add('Finish this room');

        state.hiddenSpaceCards.add(SpaceCardKind.about);
        var payload = roomDisplay(state);
        expect(payload['profileVisible'], isTrue);
        expect(payload['displayName'], 'Mika');
        expect(payload['about'], isEmpty);
        expect(payload['featuredGoals'], ['Finish this room']);

        state.hiddenSpaceCards
          ..clear()
          ..add(SpaceCardKind.rightNow);
        payload = roomDisplay(state);
        expect(payload['profileVisible'], isTrue);
        expect(payload['displayName'], 'Mika');
        expect(payload['about'], 'A room for making things.');
        expect(payload['featuredGoals'], isEmpty);

        state.hiddenSpaceCards.add(SpaceCardKind.about);
        payload = roomDisplay(state);
        expect(payload['profileVisible'], isTrue);
        expect(payload['displayName'], 'Mika');
        expect(payload['about'], isEmpty);
        expect(payload['featuredGoals'], isEmpty);
      },
    );

    test('private card content never enters the public room document', () {
      const pinnedText = 'PRIVATE-PIN-SENTINEL';
      const pinnedId = 'private-pin-note-id';
      const pinnedImage = 'journal/private-pin-image.webp';
      const seasonText = 'PRIVATE-SEASON-SENTINEL';
      const seasonId = 'private-season-note-id';
      const seasonImage = 'journal/private-season-image.webp';
      final state = GameState()
        ..shareSpaceProfile = true
        ..journal = [
          Note(
            id: pinnedId,
            at: DateTime(2026, 8, 2),
            text: pinnedText,
            images: const [pinnedImage],
          ),
          Note(
            id: seasonId,
            at: DateTime(2026, 8, 3),
            text: 'Photo source note',
            images: const [seasonImage],
          ),
        ]
        ..memoryPins.add(pinnedId);
      state.setSpacePage(
        order: const [
          SpaceCardKind.thisSeason,
          SpaceCardKind.pinnedMoments,
          SpaceCardKind.about,
          SpaceCardKind.rightNow,
        ],
        hidden: const [SpaceCardKind.pinnedMoments],
        intro: 'Visitor-safe about',
        featuredGoalTitles: const [],
        seasonText: seasonText,
        seasonPhotoNoteId: seasonId,
        shareProfile: true,
      );

      final encoded = jsonEncode(roomDisplay(state));

      for (final privateValue in const [
        pinnedText,
        pinnedId,
        pinnedImage,
        seasonText,
        seasonId,
        seasonImage,
        'spaceCardOrder',
        'hiddenSpaceCards',
        'spaceSeasonText',
        'spaceSeasonPhotoNoteId',
      ]) {
        expect(encoded, isNot(contains(privateValue)));
      }
    });

    test('rules retain v1/v2 while requiring the bounded v3 profile', () {
      final rules = _firestoreRules();

      expect(rules, contains('(d.v == 1'));
      expect(rules, contains('(d.v == 2'));
      expect(rules, contains('(d.v == 3'));
      expect(rules, contains('d.profileVisible is bool'));
      expect(rules, contains('d.displayName.size() <= 40'));
      expect(rules, contains('d.about.size() <= 180'));
      expect(rules, contains('d.featuredGoals.size() <= 3'));
      expect(rules, contains("d.displayName == ''"));
    });
  });

  test('room codes allow public get but never collection listing', () {
    final rules = _firestoreRules();
    final roomsStart = rules.indexOf(r'match /rooms/{code}');
    final sparksStart = rules.indexOf(r'match /sparks/{senderId}', roomsStart);
    expect(roomsStart, greaterThanOrEqualTo(0));
    expect(sparksStart, greaterThan(roomsStart));
    final roomRules = rules.substring(roomsStart, sparksStart);

    expect(roomRules, matches(RegExp(r'allow\s+get:\s*if\s+true;')));
    expect(roomRules, matches(RegExp(r'allow\s+list:\s*if\s+false;')));
    expect(roomRules, isNot(matches(RegExp(r'allow\s+list:\s*if\s+true;'))));
  });

  testWidgets('visit validates, loads, and retries without dismissing', (
    tester,
  ) async {
    tester.view.devicePixelRatio = 1;
    await tester.binding.setSurfaceSize(const Size(320, 568));
    tester.platformDispatcher.textScaleFactorTestValue = 1.5;
    addTearDown(() {
      tester.view.resetDevicePixelRatio();
      tester.binding.setSurfaceSize(null);
      tester.platformDispatcher.clearTextScaleFactorTestValue();
    });

    var fetches = 0;
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Builder(
            builder: (context) => FilledButton(
              onPressed: () => visitSpace(
                context,
                fetcher: (code) async {
                  fetches++;
                  expect(code, 'ABC234');
                  await Future<void>.delayed(const Duration(milliseconds: 20));
                  if (fetches == 1) throw StateError('offline');
                  return null;
                },
              ),
              child: const Text('Open visit'),
            ),
          ),
        ),
      ),
    );

    await tester.tap(find.text('Open visit'));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(const Key('visit-space-code')), 'bad');
    await tester.tap(find.byKey(const Key('visit-space-submit')));
    await tester.pump();
    expect(fetches, 0);
    expect(find.byKey(const Key('visit-space-error')), findsOneWidget);

    await tester.enterText(find.byKey(const Key('visit-space-code')), 'abc234');
    await tester.tap(find.byKey(const Key('visit-space-submit')));
    await tester.pump();
    expect(find.byKey(const Key('visit-space-loading')), findsOneWidget);
    expect(find.text('Visit a space'), findsOneWidget);
    await tester.pump(const Duration(milliseconds: 20));
    await tester.pump();
    expect(fetches, 1);
    expect(find.byKey(const Key('visit-space-error')), findsOneWidget);
    expect(find.textContaining('Couldn’t reach'), findsOneWidget);
    expect(find.text('Visit a space'), findsOneWidget);

    await tester.tap(find.byKey(const Key('visit-space-submit')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 20));
    await tester.pump();
    expect(fetches, 2);
    expect(find.textContaining('No shared space found'), findsOneWidget);
    expect(tester.takeException(), isNull);
  });

  testWidgets('share Done remains reachable at large text', (tester) async {
    tester.view.devicePixelRatio = 1;
    await tester.binding.setSurfaceSize(const Size(320, 568));
    tester.platformDispatcher.textScaleFactorTestValue = 2;
    addTearDown(() {
      tester.view.resetDevicePixelRatio();
      tester.binding.setSurfaceSize(null);
      tester.platformDispatcher.clearTextScaleFactorTestValue();
    });

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Builder(
            builder: (context) => FilledButton(
              onPressed: () => showShareSpaceDialog(
                context,
                code: 'ABC234',
                onStop: () async => true,
              ),
              child: const Text('Open share'),
            ),
          ),
        ),
      ),
    );

    await tester.tap(find.text('Open share'));
    await tester.pumpAndSettle();
    expect(find.byKey(const Key('share-space-done')), findsOneWidget);
    expect(tester.takeException(), isNull);
    await tester.tap(find.byKey(const Key('share-space-done')));
    await tester.pumpAndSettle();
    expect(find.text('Your space is live'), findsNothing);
    expect(tester.takeException(), isNull);
  });
}
